Repository Arquisoft/dede_es2b, pull requests merged in 2022-02, with the labels that each got.

#14 Pull Request sobre puntos 1 y 2 hechos de documentación.
  docs/01_introduction_and_goals.adoc
  docs/02_architecture_constraints.adoc
  docs/package-lock.json
  restapi/package-lock.json
  webapp/package-lock.json
Labels: Documentación

#16 Puntos 4 y 7 de documentación.
  docs/04_solution_strategy.adoc
  docs/07_deployment_view.adoc
  package-lock.json
Labels: Documentación

#17 Añadido diagrama al punto 3
  docs/images/Diagrama3.png
Labels: Documentación

#31 Adrián
  docs/10_quality_scenarios.adoc
  docs/11_technical_risks.adoc
  docs/index.adoc
Labels: Documentación 📑

#40 Diagrama apartado 6 - Ver pedidos
  docs/06_runtime_view.adoc
Labels: Documentación 📑, Diagramas 📊

#41 Corrección de símbolos =
  docs/06_runtime_view.adoc
Labels: bug 🚨, Documentación 📑, Diagramas 📊
