Repository Arquisoft/dede_es2b, pull requests merged in 2022-03, with the labels that each got.

#53 Nuevas peticiones y encriptacion de contraseñas
  restapi/api.ts
  restapi/package-lock.json
  restapi/package.json
  restapi/schemas/Pedido.ts
  restapi/schemas/Usuario.ts
  restapi/schemas/Validators.ts
  restapi/server.ts
  webapp/src/api/api.ts
  webapp/src/shared/shareddtypes.ts
Labels: Back End

#56 Hecho mostrar productos de la base de datos
  restapi/api.ts
  restapi/package-lock.json
  restapi/schemas/Producto.ts
  webapp/src/App.tsx
  webapp/src/api/api.ts
  webapp/src/components/ProductItem.tsx
  webapp/src/components/Products.tsx
  webapp/src/shared/shareddtypes.ts
Labels: Back End

#59 Villa
  restapi/package-lock.json
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.tsx
  webapp/src/api/api.ts
  webapp/src/components/HomeNavBar.tsx
  webapp/src/components/login/Login.tsx
  webapp/src/components/login/LoginNavBar.tsx
  webapp/src/components/login/LoginScreen.tsx
  webapp/src/index.tsx
  webapp/src/shared/shareddtypes.ts
Labels: Frontend 🖥

#65 Ligera actualizacion del glosario con las librerias usadas hasta ahora en backend
  docs/11_technical_risks.adoc
  docs/12_glossary.adoc
Labels: 📑 Documentación 📑

#71 Pantalla registro
  webapp/src/components/login/Register.tsx
  webapp/src/components/login/RegisterScreen.tsx
Labels: 🖥 Front End 🔚

#115 Actualización puntos 7 y 12 documentación
  .github/workflows/asw2122.yml
  docs/07_deployment_view.adoc
  docs/12_glossary.adoc
  restapi/Carrito/Cart.ts
  restapi/Carrito/apiCarrito.ts
  restapi/package.json
  restapi/pedidos/PedidoSchema.ts
  restapi/pedidos/apiPedidos.ts
  restapi/productos/apiProductos.ts
  restapi/schemas/Validators.ts
  restapi/server.ts
  restapi/tests/api.test.ts
  restapi/tests/apiPedidos.test.ts
  restapi/tests/apiProductos.test.ts
  restapi/tests/apiUsuarios.test.ts
  restapi/tests/jest.config.ts
  restapi/tests/mockData.json
  restapi/tests/setServerForTests.ts
  restapi/tsconfig.json
  restapi/usuarios/UsuarioSchema.ts
  restapi/usuarios/apiUsuarios.ts
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.tsx
  webapp/src/api/api.ts
  webapp/src/components/EmailForm.test.tsx
  webapp/src/components/EmailForm.tsx
  webapp/src/components/HomeNavBar.tsx
  webapp/src/components/NavBar.tsx
  webapp/src/components/UserList.test.tsx
  webapp/src/components/UserList.tsx
  webapp/src/components/Welcome.test.tsx
  webapp/src/components/Welcome.tsx
  webapp/src/components/carrito/Carrito.tsx
  webapp/src/components/carrito/CarritoItem.tsx
  webapp/src/components/carrito/Total.tsx
  webapp/src/components/login/Login.tsx
  webapp/src/components/login/LoginNavBar.tsx
  webapp/src/components/login/LoginScreen.tsx
  webapp/src/components/login/Register.tsx
  webapp/src/components/pedidos/ListaPedidos.tsx
  webapp/src/components/product/ProductItem.tsx
  webapp/src/components/product/Products.tsx
  webapp/src/shared/shareddtypes.ts
Labels: 📑 Documentación 📑
