Repository Arquisoft/dede_es2b, pull requests merged in 2022-05, with the labels that each got.

#226 Pantallas de pago y listar usuarios
  webapp/src/App.tsx
  webapp/src/components/NavBar.tsx
  webapp/src/components/carrito/Carrito.tsx
  webapp/src/components/login/Login.tsx
  webapp/src/components/pago/Pago.tsx
  webapp/src/components/pago/PopUpSolid.css
  webapp/src/components/usuario/ListaUsuarios.tsx
  webapp/src/shared/shareddtypes.ts
Labels: 🖥 Front End 🔚

#242 Pantalla pedido completado
  docs/07_deployment_view.adoc
  webapp/src/components/pago/Tarjeta.tsx
  webapp/src/components/pedidoCompletado/PedidoCompletado.tsx
Labels: 🖥 Front End 🔚

#254 Comprobación tarjeta caducada
  webapp/src/components/pago/Pago.tsx
  webapp/src/components/pago/Tarjeta.tsx
Labels: 🚨 Bug 🚨

#255 Base de los test e2e de Pago
  docs/01_introduction_and_goals.adoc
  docs/05_building_block_view.adoc
  docs/images/05_diagrama_general.jpg
  docs/images/05_diagrama_nivel_1.jpg
  docs/images/05_diagrama_nivel_2.jpg
  docs/images/05_diagrama_nivel_3.jpg
  docs/images/05_diagrama_nivel_3p.pdn
  webapp/e2e/features/pay-test.feature
  webapp/e2e/steps/pay-test.steps.ts
  webapp/src/components/usuario/ListaUsuarios.tsx
Labels: 🔐 Tests 🔐, 👁‍🗨 Revisión 👁‍🗨
