Repository Arquisoft/dede_es2b, pull requests merged in 2022-04, with the labels that each got.

#133 Tests pantallas de login y registro
  webapp/src/components/login/Register.tsx
  webapp/src/tests/login.test.tsx
  webapp/src/tests/loginScreen.test.tsx
  webapp/src/tests/register.test.tsx
Labels: 🖥 Front End 🔚, Tests

#162 Añadir imágenes Wiki
  docs/images/Imagenes Wiki/BaseParaPortadas.png
  docs/images/Imagenes Wiki/Portada1.png
  docs/images/Imagenes Wiki/Portada10.png
  docs/images/Imagenes Wiki/Portada2.png
  docs/images/Imagenes Wiki/Portada3.png
  docs/images/Imagenes Wiki/Portada4.png
  docs/images/Imagenes Wiki/Portada5.png
  docs/images/Imagenes Wiki/Portada6.png
  docs/images/Imagenes Wiki/Portada7.png
  docs/images/Imagenes Wiki/Portada8.png
  docs/images/Imagenes Wiki/Portada9.png
Labels: 📑 Documentación 📑, 🌍 Wiki 🌍

#169 Añadido vista de añadir productos
  webapp/src/App.tsx
  webapp/src/components/carrito/Carrito.tsx
  webapp/src/components/product/AñadirProducto.tsx
  webapp/src/components/product/ProductItem.tsx
  webapp/src/components/product/Products.tsx
Labels: 🖥 Front End 🔚

#176 Actualizar doc 3
  docs/03_system_scope_and_context.adoc
  docs/images/03_Diagrama_Contexto_Empresarial.PNG
  docs/images/03_Diagrama_Contexto_Tecnico.PNG
Labels: 📑 Documentación 📑, 📊 Diagramas 📊

#184 Añadir documentación actualizada
  docs/01_introduction_and_goals.adoc
  docs/02_architecture_constraints.adoc
  docs/03_system_scope_and_context.adoc
  docs/09_design_decisions.adoc
  docs/12_glossary.adoc
  docs/images/3_Diagrama_Contexto_Empresarial.PNG
Labels: 📑 Documentación 📑, 📊 Diagramas 📊

#188 Actualización de diagramas doc6
  docs/06_runtime_view.adoc
Labels: 📑 Documentación 📑, 📊 Diagramas 📊

#189 Arreglado test
  webapp/src/App.test.tsx
Labels: Tests

#213 Pantalla pago
  webapp/src/App.tsx
  webapp/src/components/carrito/Carrito.tsx
  webapp/src/components/carrito/Total.tsx
  webapp/src/components/login/Login.tsx
  webapp/src/components/pago/Pago.tsx
Labels: 🖥 Front End 🔚
